-- Run once in the Supabase SQL editor, AFTER ops_hub_phase1..5.
--
-- TRC Operations Hub — PHASE 6 (notifications). The subset of the activity spine
-- that a SPECIFIC person needs to act on — NOT the feed (which is everything).
-- Generated by a TRIGGER on activity_events so it catches EVERY event, including
-- those the materialiser cron emits outside the app (recurring-task assignments)
-- — the same unbypassable-chokepoint principle as the spine itself.
--
-- Recipient is a profiles.id (a login identity). An event targeting a team_member
-- resolves via team_members.profile_id; a name-only member (no profile) yields NO
-- notification (nothing to deliver — honest). Self-notification is skipped.
--
-- Idempotent / re-runnable.

begin;

create table if not exists notifications (
  id           uuid primary key default gen_random_uuid(),
  recipient    uuid not null references profiles(id) on delete cascade,
  type         text not null,   -- task_assigned | task_completed | shift_assigned | shift_updated | shift_removed | task_due_soon
  event_id     uuid references activity_events(id) on delete set null,  -- null for cron-derived (due_soon)
  metadata     jsonb not null default '{}'::jsonb,   -- snapshot: label + click-through link
  read         boolean not null default false,
  read_at      timestamptz,
  email_status text not null default 'in_app_only',  -- in_app_only | pending | sent | failed | skipped
  created_at   timestamptz not null default now()
);
create index if not exists idx_notifications_recipient on notifications(recipient, read, created_at desc);
create index if not exists idx_notifications_email_pending on notifications(email_status) where email_status = 'pending';

-- Editable per-type email-worthiness (seeded with the agreed defaults; tune live).
create table if not exists notification_email_types (
  type          text primary key,
  email_enabled boolean not null default false
);
insert into notification_email_types (type, email_enabled) values
  ('task_assigned',  true),
  ('shift_assigned', true),
  ('shift_updated',  true),
  ('shift_removed',  true),
  ('task_due_soon',  true),
  ('task_completed', false)
on conflict (type) do nothing;

-- Delivery log — every email attempt + result, so failures are visible/retryable.
create table if not exists notification_deliveries (
  id              uuid primary key default gen_random_uuid(),
  notification_id uuid not null references notifications(id) on delete cascade,
  channel         text not null,        -- 'email'
  status          text not null,        -- sent | failed | skipped
  detail          text,
  created_at      timestamptz not null default now()
);
create index if not exists idx_notif_deliveries on notification_deliveries(notification_id);

-- ── helpers ──
create or replace function ops_member_profile(p_member uuid)
  returns uuid language sql security definer set search_path = public stable as $$
  select profile_id from team_members where id = p_member;
$$;

-- Create a notification — skips null recipient and self-notification; sets
-- email_status from the editable per-type config.
create or replace function ops_make_notification(
  p_recipient uuid, p_actor uuid, p_type text, p_event_id uuid, p_metadata jsonb
) returns void language plpgsql security definer set search_path = public as $$
declare v_email boolean;
begin
  if p_recipient is null then return; end if;        -- nothing to deliver
  if p_recipient = p_actor then return; end if;      -- don't notify yourself
  select email_enabled into v_email from notification_email_types where type = p_type;
  insert into notifications (recipient, type, event_id, metadata, email_status)
  values (p_recipient, p_type, p_event_id, coalesce(p_metadata, '{}'::jsonb),
          case when coalesce(v_email, false) then 'pending' else 'in_app_only' end);
end$$;

-- ── THE TRIGGER: generate notifications from every activity event ──
create or replace function notify_from_event()
  returns trigger language plpgsql security definer set search_path = public as $$
declare v_assignee uuid; v_recipient uuid;
begin
  -- TASK assigned, OR created-already-assigned (manual or the materialiser's
  -- auto-assign — both surface as an assignee on the event, so both notify).
  if NEW.object_type = 'task' and NEW.verb in ('assigned', 'created') then
    v_assignee := nullif(NEW.metadata->>'assignee', '')::uuid;
    if v_assignee is not null then
      perform ops_make_notification(ops_member_profile(v_assignee), NEW.actor, 'task_assigned', NEW.id,
        jsonb_build_object('title', NEW.metadata->>'title', 'link', '/admin/ops/' || NEW.project_id));
    end if;

  elsif NEW.object_type = 'task' and NEW.verb = 'completed' then
    select assignee into v_assignee from tasks where id = NEW.object_id;  -- completed event has no assignee in metadata
    if v_assignee is not null then
      perform ops_make_notification(ops_member_profile(v_assignee), NEW.actor, 'task_completed', NEW.id,
        jsonb_build_object('title', NEW.metadata->>'title', 'link', '/admin/ops/' || NEW.project_id));
    end if;

  elsif NEW.object_type = 'shift' and NEW.verb in ('assigned', 'updated', 'removed') then
    v_assignee := nullif(NEW.metadata->>'member', '')::uuid;
    if v_assignee is not null then
      perform ops_make_notification(ops_member_profile(v_assignee), NEW.actor,
        case NEW.verb when 'assigned' then 'shift_assigned' when 'updated' then 'shift_updated' else 'shift_removed' end,
        NEW.id,
        jsonb_build_object('shift_name', NEW.metadata->>'shift_name', 'shift_date', NEW.metadata->>'shift_date', 'link', '/admin/ops/rota'));
    end if;
  end if;
  -- everything else (created-unassigned, moved, reordered, linked, archived,
  -- member_added, template:*, project:*) → no notification (feed's job).
  return NEW;
end$$;

drop trigger if exists trg_notify_from_event on activity_events;
create trigger trg_notify_from_event after insert on activity_events
  for each row execute function notify_from_event();

-- ── due-soon generator (run by the daily cron — no event triggers this) ──
-- Notifies the assignee's profile AND the owner (created_by), de-duplicated,
-- for tasks due on the given VN day. Idempotent: skips a (task,recipient) that
-- already got a due_soon notification in the last 20h.
create or replace function ops_generate_due_soon(p_due_date date default null)
  returns integer language plpgsql security definer set search_path = public as $$
declare v_date date := coalesce(p_due_date, (ops_today_vn() + 1)); t record; v_made int := 0;
begin
  for t in
    select tk.id, tk.project_id, tk.title, tk.created_by,
           tm.profile_id as assignee_profile
      from tasks tk
      left join team_members tm on tm.id = tk.assignee
     where tk.due_date = v_date
       and tk.completed_at is null
       and tk.status <> 'lapsed'
  loop
    -- recipients = assignee's profile + owner, de-duplicated, non-null
    -- assignee
    if t.assignee_profile is not null
       and not exists (select 1 from notifications n where n.type='task_due_soon'
                       and n.recipient=t.assignee_profile and n.metadata->>'task_id'=t.id::text
                       and n.created_at > now() - interval '20 hours') then
      insert into notifications (recipient, type, event_id, metadata, email_status)
      values (t.assignee_profile, 'task_due_soon', null,
              jsonb_build_object('title', t.title, 'task_id', t.id, 'link', '/admin/ops/' || t.project_id),
              case when (select email_enabled from notification_email_types where type='task_due_soon') then 'pending' else 'in_app_only' end);
      v_made := v_made + 1;
    end if;
    -- owner (created_by), only if different from the assignee profile
    if t.created_by is not null and t.created_by is distinct from t.assignee_profile
       and not exists (select 1 from notifications n where n.type='task_due_soon'
                       and n.recipient=t.created_by and n.metadata->>'task_id'=t.id::text
                       and n.created_at > now() - interval '20 hours') then
      insert into notifications (recipient, type, event_id, metadata, email_status)
      values (t.created_by, 'task_due_soon', null,
              jsonb_build_object('title', t.title, 'task_id', t.id, 'link', '/admin/ops/' || t.project_id),
              case when (select email_enabled from notification_email_types where type='task_due_soon') then 'pending' else 'in_app_only' end);
      v_made := v_made + 1;
    end if;
  end loop;
  return v_made;
end$$;

-- ── mark read ──
create or replace function ops_mark_notification_read(p_id uuid)
  returns void language plpgsql security invoker set search_path = public as $$
begin
  update notifications set read = true, read_at = now() where id = p_id and recipient = auth.uid();
end$$;

create or replace function ops_mark_all_notifications_read()
  returns void language plpgsql security invoker set search_path = public as $$
begin
  update notifications set read = true, read_at = now() where recipient = auth.uid() and not read;
end$$;

-- ── RLS ──
alter table notifications            enable row level security;
alter table notification_email_types enable row level security;
alter table notification_deliveries  enable row level security;

drop policy if exists "notifications own" on notifications;
create policy "notifications own" on notifications
  for select using (recipient = auth.uid() or is_admin_uid(auth.uid()));
drop policy if exists "notifications update own" on notifications;
create policy "notifications update own" on notifications
  for update using (recipient = auth.uid()) with check (recipient = auth.uid());

drop policy if exists "email types read" on notification_email_types;
create policy "email types read" on notification_email_types for select using (true);
drop policy if exists "email types admin write" on notification_email_types;
create policy "email types admin write" on notification_email_types
  for all using (is_admin_uid(auth.uid())) with check (is_admin_uid(auth.uid()));

drop policy if exists "deliveries admin read" on notification_deliveries;
create policy "deliveries admin read" on notification_deliveries
  for select using (is_admin_uid(auth.uid()));

grant execute on function ops_mark_notification_read(uuid)        to authenticated;
grant execute on function ops_mark_all_notifications_read()       to authenticated;
grant execute on function ops_generate_due_soon(date)             to authenticated, service_role;

commit;

-- Verify (after this migration): run ops_hub_phase6_verify.sql.
