-- ─────────────────────────────────────────────────────────────────────────
-- Whisky flavour tags — FOUNDATION for the (later) recommendation engine + radar.
-- GENERATED by scripts/whisky-flavour-tags.mjs (emit-sql) — taxonomy is the
-- single source of truth in that file; regenerate, don't hand-edit the seed.
--
-- Three tables:
--   flavour_categories      — tier 1, the 12 broad families.
--   flavour_descriptors     — tier 2, finer notes under each family.
--   whisky_flavour_intensities — per-(bottle, broad-category) INTENSITY 1-4 +
--       confidence. These are the radar/spider spoke lengths (absent = spoke 0).
--   whisky_flavour_tags     — per-(bottle, descriptor) fine tags + confidence +
--       evidence. Both tag tables carry a confirmed flag (machine proposes,
--       human ratifies — like the MIS preference-candidate queue).
-- Tags AUGMENT whiskies; existing fields untouched.
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists flavour_categories (
  slug        text primary key,
  name        text not null,
  description text,
  sort_order  int  not null default 0
);

create table if not exists flavour_descriptors (
  slug          text primary key,
  category_slug text not null references flavour_categories(slug) on delete cascade,
  name          text not null,
  sort_order    int  not null default 0
);

-- The radar spokes: one row per broad category the PROSE supports, with how
-- strong it is (intensity 1-4) and how sure we are it's present (confidence).
create table if not exists whisky_flavour_intensities (
  id            uuid primary key default gen_random_uuid(),
  whisky_id     uuid not null references whiskies(id) on delete cascade,
  category_slug text not null references flavour_categories(slug),
  intensity     smallint not null check (intensity between 1 and 4),
  confidence    numeric(3,2) not null check (confidence >= 0 and confidence <= 1),
  source        text not null default 'llm',
  model         text,
  evidence      text,
  confirmed     boolean not null default false,
  created_at    timestamptz not null default now(),
  unique (whisky_id, category_slug)             -- one spoke per category per bottle
);
create index if not exists idx_wfi_whisky    on whisky_flavour_intensities(whisky_id);
create index if not exists idx_wfi_confirmed on whisky_flavour_intensities(confirmed);

-- The fine descriptor tags (tier 2).
create table if not exists whisky_flavour_tags (
  id              uuid primary key default gen_random_uuid(),
  whisky_id       uuid not null references whiskies(id) on delete cascade,
  category_slug   text not null references flavour_categories(slug),
  descriptor_slug text not null references flavour_descriptors(slug),
  confidence      numeric(3,2) not null check (confidence >= 0 and confidence <= 1),
  source          text not null default 'llm',
  model           text,
  evidence        text,
  confirmed       boolean not null default false,
  created_at      timestamptz not null default now(),
  unique (whisky_id, category_slug, descriptor_slug)
);
create index if not exists idx_wft_whisky    on whisky_flavour_tags(whisky_id);
create index if not exists idx_wft_confirmed on whisky_flavour_tags(confirmed);
create index if not exists idx_wft_category  on whisky_flavour_tags(category_slug);

-- RLS — mirror whiskies: members read, admins write.
alter table flavour_categories          enable row level security;
alter table flavour_descriptors         enable row level security;
alter table whisky_flavour_intensities  enable row level security;
alter table whisky_flavour_tags         enable row level security;

drop policy if exists "read flavour_categories" on flavour_categories;
create policy "read flavour_categories" on flavour_categories for select using (auth.uid() is not null);
drop policy if exists "admins write flavour_categories" on flavour_categories;
create policy "admins write flavour_categories" on flavour_categories for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));
drop policy if exists "read flavour_descriptors" on flavour_descriptors;
create policy "read flavour_descriptors" on flavour_descriptors for select using (auth.uid() is not null);
drop policy if exists "admins write flavour_descriptors" on flavour_descriptors;
create policy "admins write flavour_descriptors" on flavour_descriptors for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));
drop policy if exists "read whisky_flavour_intensities" on whisky_flavour_intensities;
create policy "read whisky_flavour_intensities" on whisky_flavour_intensities for select using (auth.uid() is not null);
drop policy if exists "admins write whisky_flavour_intensities" on whisky_flavour_intensities;
create policy "admins write whisky_flavour_intensities" on whisky_flavour_intensities for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));
drop policy if exists "read whisky_flavour_tags" on whisky_flavour_tags;
create policy "read whisky_flavour_tags" on whisky_flavour_tags for select using (auth.uid() is not null);
drop policy if exists "admins write whisky_flavour_tags" on whisky_flavour_tags;
create policy "admins write whisky_flavour_tags" on whisky_flavour_tags for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));

-- ── Taxonomy seed (generated from TAXONOMY) ──
insert into flavour_categories (slug, name, description, sort_order) values ('young_spritely', 'Young & Spritely', 'Fresh, vibrant, cereal-led; little cask influence.', 1)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('sweet_fruity_mellow', 'Sweet, Fruity & Mellow', 'Soft orchard/stone fruit, honey and vanilla; rounded and easy.', 2)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('spicy_sweet', 'Spicy & Sweet', 'Warming baking spice over a sweet base.', 3)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('spicy_dry', 'Spicy & Dry', 'Drying oak spice, pepper, tannin, tobacco/leather.', 4)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('rich_dried_fruits', 'Deep, Rich & Dried Fruits', 'Classic sherry cask: raisin, fig, dark chocolate, christmas cake.', 5)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('old_dignified', 'Old & Dignified', 'Mature, polished oak; beeswax, old leather, dried herbs.', 6)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('light_delicate', 'Light & Delicate', 'Gentle, floral, light honey and lemon; subtle malt.', 7)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('juicy_oak_vanilla', 'Juicy, Oak & Vanilla', 'Bourbon-cask sweetness: vanilla, coconut, toasted oak, custard.', 8)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('oily_coastal', 'Oily & Coastal', 'Maritime: brine, sea salt, seaweed, oily texture, minerality.', 9)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('lightly_peated', 'Lightly Peated', 'A gentle wisp of smoke over a non-peaty base.', 10)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('peated', 'Peated', 'Clear peat smoke: bonfire, soot, tar, smoked meat, ash.', 11)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('heavily_peated', 'Heavily Peated', 'Intense, medicinal peat: iodine, TCP, creosote, kippers.', 12)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, sort_order) values ('grain_rye', 'Grain & Rye', 'Grain-whisky and rye character: rye spice, corn, cereal sweetness, raw wood.', 13)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;

insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('cereal__young_spritely', 'young_spritely', 'Cereal', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('grassy__young_spritely', 'young_spritely', 'Grassy', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('green_apple__young_spritely', 'young_spritely', 'Green Apple', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('citrus_zest__young_spritely', 'young_spritely', 'Citrus Zest', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('floral__young_spritely', 'young_spritely', 'Floral', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('fresh_malt__young_spritely', 'young_spritely', 'Fresh Malt', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('vanilla__sweet_fruity_mellow', 'sweet_fruity_mellow', 'Vanilla', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('honey__sweet_fruity_mellow', 'sweet_fruity_mellow', 'Honey', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('orchard_fruit__sweet_fruity_mellow', 'sweet_fruity_mellow', 'Orchard Fruit', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('caramel__sweet_fruity_mellow', 'sweet_fruity_mellow', 'Caramel', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('stone_fruit__sweet_fruity_mellow', 'sweet_fruity_mellow', 'Stone Fruit', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('toffee__sweet_fruity_mellow', 'sweet_fruity_mellow', 'Toffee', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('cinnamon__spicy_sweet', 'spicy_sweet', 'Cinnamon', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('ginger__spicy_sweet', 'spicy_sweet', 'Ginger', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('nutmeg__spicy_sweet', 'spicy_sweet', 'Nutmeg', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('baking_spice__spicy_sweet', 'spicy_sweet', 'Baking Spice', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('clove__spicy_sweet', 'spicy_sweet', 'Clove', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('honeyed_spice__spicy_sweet', 'spicy_sweet', 'Honeyed Spice', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('black_pepper__spicy_dry', 'spicy_dry', 'Black Pepper', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('oak_tannin__spicy_dry', 'spicy_dry', 'Oak Tannin', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('dry_spice__spicy_dry', 'spicy_dry', 'Dry Spice', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('tobacco__spicy_dry', 'spicy_dry', 'Tobacco', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('leather__spicy_dry', 'spicy_dry', 'Leather', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('char__spicy_dry', 'spicy_dry', 'Char', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('clove__spicy_dry', 'spicy_dry', 'Clove', 6)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('raisin__rich_dried_fruits', 'rich_dried_fruits', 'Raisin', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('fig__rich_dried_fruits', 'rich_dried_fruits', 'Fig', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('date__rich_dried_fruits', 'rich_dried_fruits', 'Date', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('dark_chocolate__rich_dried_fruits', 'rich_dried_fruits', 'Dark Chocolate', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('christmas_cake__rich_dried_fruits', 'rich_dried_fruits', 'Christmas Cake', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('walnut__rich_dried_fruits', 'rich_dried_fruits', 'Walnut', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('dried_fruit__rich_dried_fruits', 'rich_dried_fruits', 'Dried Fruit', 6)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('polished_oak__old_dignified', 'old_dignified', 'Polished Oak', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('beeswax__old_dignified', 'old_dignified', 'Beeswax', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('old_leather__old_dignified', 'old_dignified', 'Old Leather', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('dried_herbs__old_dignified', 'old_dignified', 'Dried Herbs', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('sandalwood__old_dignified', 'old_dignified', 'Sandalwood', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('antique_wood__old_dignified', 'old_dignified', 'Antique Wood', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('floral__light_delicate', 'light_delicate', 'Floral', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('light_honey__light_delicate', 'light_delicate', 'Light Honey', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('lemon__light_delicate', 'light_delicate', 'Lemon', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('hay__light_delicate', 'light_delicate', 'Hay', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('delicate_malt__light_delicate', 'light_delicate', 'Delicate Malt', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('meadow__light_delicate', 'light_delicate', 'Meadow', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('vanilla__juicy_oak_vanilla', 'juicy_oak_vanilla', 'Vanilla', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('coconut__juicy_oak_vanilla', 'juicy_oak_vanilla', 'Coconut', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('toasted_oak__juicy_oak_vanilla', 'juicy_oak_vanilla', 'Toasted Oak', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('butterscotch__juicy_oak_vanilla', 'juicy_oak_vanilla', 'Butterscotch', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('custard__juicy_oak_vanilla', 'juicy_oak_vanilla', 'Custard', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('banana__juicy_oak_vanilla', 'juicy_oak_vanilla', 'Banana', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('brine__oily_coastal', 'oily_coastal', 'Brine', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('sea_salt__oily_coastal', 'oily_coastal', 'Sea Salt', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('seaweed__oily_coastal', 'oily_coastal', 'Seaweed', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('oily_texture__oily_coastal', 'oily_coastal', 'Oily Texture', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('mineral__oily_coastal', 'oily_coastal', 'Mineral', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('smoked_fish__oily_coastal', 'oily_coastal', 'Smoked Fish', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('gentle_smoke__lightly_peated', 'lightly_peated', 'Gentle Smoke', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('soft_peat__lightly_peated', 'lightly_peated', 'Soft Peat', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('ember__lightly_peated', 'lightly_peated', 'Ember', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('light_bonfire__lightly_peated', 'lightly_peated', 'Light Bonfire', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('bonfire_smoke__peated', 'peated', 'Bonfire Smoke', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('soot__peated', 'peated', 'Soot', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('tar__peated', 'peated', 'Tar', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('smoked_meat__peated', 'peated', 'Smoked Meat', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('ash__peated', 'peated', 'Ash', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('campfire__peated', 'peated', 'Campfire', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('medicinal__heavily_peated', 'heavily_peated', 'Medicinal', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('iodine__heavily_peated', 'heavily_peated', 'Iodine', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('tcp__heavily_peated', 'heavily_peated', 'Tcp', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('creosote__heavily_peated', 'heavily_peated', 'Creosote', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('intense_smoke__heavily_peated', 'heavily_peated', 'Intense Smoke', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('kippers__heavily_peated', 'heavily_peated', 'Kippers', 5)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('rye_spice__grain_rye', 'grain_rye', 'Rye Spice', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('corn__grain_rye', 'grain_rye', 'Corn', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('grain__grain_rye', 'grain_rye', 'Grain', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('sawdust__grain_rye', 'grain_rye', 'Sawdust', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('cereal_sweetness__grain_rye', 'grain_rye', 'Cereal Sweetness', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
