-- ─────────────────────────────────────────────────────────────────────────
-- Whisky flavour tags — FOUNDATION for the (later) recommendation engine + radar.
-- GENERATED by scripts/whisky-flavour-tags.mjs (emit-sql) — taxonomy is the
-- single source of truth in that file; regenerate, don't hand-edit the seed.
--
-- Three tables:
--   flavour_categories      — tier 1, the 16 Compass families (+ quadrant).
--   flavour_descriptors     — tier 2, finer notes under each family.
--   whisky_flavour_intensities — per-(bottle, broad-category) INTENSITY 1-4 +
--       confidence. These are the radar/spider spoke lengths (absent = spoke 0).
--   whisky_flavour_tags     — per-(bottle, descriptor) fine tags + confidence +
--       evidence. Both tag tables carry a confirmed flag (machine proposes,
--       human ratifies — like the MIS preference-candidate queue).
-- Tags AUGMENT whiskies; existing fields untouched.
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists flavour_categories (
  slug        text primary key,
  name        text not null,
  description text,
  quadrant    text,
  sort_order  int  not null default 0
);
alter table flavour_categories add column if not exists quadrant text;

create table if not exists flavour_descriptors (
  slug          text primary key,
  category_slug text not null references flavour_categories(slug) on delete cascade,
  name          text not null,
  sort_order    int  not null default 0
);

-- The radar spokes: one row per broad category the PROSE supports, with how
-- strong it is (intensity 1-4) and how sure we are it's present (confidence).
create table if not exists whisky_flavour_intensities (
  id            uuid primary key default gen_random_uuid(),
  whisky_id     uuid not null references whiskies(id) on delete cascade,
  category_slug text not null references flavour_categories(slug),
  intensity     smallint not null check (intensity between 1 and 4),
  confidence    numeric(3,2) not null check (confidence >= 0 and confidence <= 1),
  source        text not null default 'llm',
  model         text,
  evidence      text,
  confirmed     boolean not null default false,
  created_at    timestamptz not null default now(),
  unique (whisky_id, category_slug)             -- one spoke per category per bottle
);
create index if not exists idx_wfi_whisky    on whisky_flavour_intensities(whisky_id);
create index if not exists idx_wfi_confirmed on whisky_flavour_intensities(confirmed);

-- The fine descriptor tags (tier 2).
create table if not exists whisky_flavour_tags (
  id              uuid primary key default gen_random_uuid(),
  whisky_id       uuid not null references whiskies(id) on delete cascade,
  category_slug   text not null references flavour_categories(slug),
  descriptor_slug text not null references flavour_descriptors(slug),
  confidence      numeric(3,2) not null check (confidence >= 0 and confidence <= 1),
  source          text not null default 'llm',
  model           text,
  evidence        text,
  confirmed       boolean not null default false,
  created_at      timestamptz not null default now(),
  unique (whisky_id, category_slug, descriptor_slug)
);
create index if not exists idx_wft_whisky    on whisky_flavour_tags(whisky_id);
create index if not exists idx_wft_confirmed on whisky_flavour_tags(confirmed);
create index if not exists idx_wft_category  on whisky_flavour_tags(category_slug);

-- RLS — mirror whiskies: members read, admins write.
alter table flavour_categories          enable row level security;
alter table flavour_descriptors         enable row level security;
alter table whisky_flavour_intensities  enable row level security;
alter table whisky_flavour_tags         enable row level security;

drop policy if exists "read flavour_categories" on flavour_categories;
create policy "read flavour_categories" on flavour_categories for select using (auth.uid() is not null);
drop policy if exists "admins write flavour_categories" on flavour_categories;
create policy "admins write flavour_categories" on flavour_categories for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));
drop policy if exists "read flavour_descriptors" on flavour_descriptors;
create policy "read flavour_descriptors" on flavour_descriptors for select using (auth.uid() is not null);
drop policy if exists "admins write flavour_descriptors" on flavour_descriptors;
create policy "admins write flavour_descriptors" on flavour_descriptors for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));
drop policy if exists "read whisky_flavour_intensities" on whisky_flavour_intensities;
create policy "read whisky_flavour_intensities" on whisky_flavour_intensities for select using (auth.uid() is not null);
drop policy if exists "admins write whisky_flavour_intensities" on whisky_flavour_intensities;
create policy "admins write whisky_flavour_intensities" on whisky_flavour_intensities for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));
drop policy if exists "read whisky_flavour_tags" on whisky_flavour_tags;
create policy "read whisky_flavour_tags" on whisky_flavour_tags for select using (auth.uid() is not null);
drop policy if exists "admins write whisky_flavour_tags" on whisky_flavour_tags;
create policy "admins write whisky_flavour_tags" on whisky_flavour_tags for all
  using  (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.is_admin = true));

-- ── Taxonomy seed (generated from TAXONOMY) ──
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('cereal_biscuit', 'Cereal & Biscuit', 'Malt loaf, biscuit, porridge, rye bread, corn.', 'field', 1)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('green_grassy', 'Green & Grassy', 'Cut grass, hay, green apple skin, leafy freshness.', 'field', 2)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('orchard_fruit', 'Orchard Fruit', 'Apple, pear, plum, apricot.', 'still', 3)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('tropical_citrus', 'Tropical & Citrus', 'Banana, pineapple, mango, lemon zest.', 'still', 4)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('floral_honeyed', 'Floral & Honeyed', 'Heather honey, rose, elderflower, beeswax.', 'still', 5)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('buttery_creamy', 'Buttery & Creamy', 'Butter, cream, custard, fudge.', 'still', 6)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('meaty_sulphury', 'Meaty & Sulphury', 'Struck match, broth, cooked meat, gunpowder.', 'still', 7)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('vanilla_coconut', 'Vanilla & Coconut', 'Vanilla, coconut, toasted-oak sweetness.', 'cask', 8)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('baking_spice', 'Baking Spice', 'Cinnamon, clove, nutmeg, ginger.', 'cask', 9)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('pepper_tannin', 'Pepper & Tannin', 'Black pepper, oak tannin, black tea, rye pepper.', 'cask', 10)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('dried_fruit_walnut', 'Dried Fruit & Walnut', 'Raisin, fig, date, walnut.', 'cask', 11)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('treacle_roast', 'Treacle & Roast', 'Toffee, treacle, coffee, dark chocolate, char.', 'cask', 12)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('leather_polished_oak', 'Leather & Polished Oak', 'Old leather, tobacco, waxed wood, dried herbs.', 'cask', 13)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('woodsmoke', 'Woodsmoke', 'Bonfire, ash, smoked meat, embers.', 'shore', 14)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('tar_iodine', 'Tar & Iodine', 'Tar, iodine, antiseptic, creosote, kippers.', 'shore', 15)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;
insert into flavour_categories (slug, name, description, quadrant, sort_order) values ('brine_shoreline', 'Brine & Shoreline', 'Sea salt, seaweed, oyster shell, wet stone.', 'shore', 16)
  on conflict (slug) do update set name = excluded.name, description = excluded.description, quadrant = excluded.quadrant, sort_order = excluded.sort_order;

insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('malt_loaf__cereal_biscuit', 'cereal_biscuit', 'Malt Loaf', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('biscuit__cereal_biscuit', 'cereal_biscuit', 'Biscuit', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('porridge__cereal_biscuit', 'cereal_biscuit', 'Porridge', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('rye_bread__cereal_biscuit', 'cereal_biscuit', 'Rye Bread', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('corn__cereal_biscuit', 'cereal_biscuit', 'Corn', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('cut_grass__green_grassy', 'green_grassy', 'Cut Grass', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('hay__green_grassy', 'green_grassy', 'Hay', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('green_apple_skin__green_grassy', 'green_grassy', 'Green Apple Skin', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('leafy__green_grassy', 'green_grassy', 'Leafy', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('apple__orchard_fruit', 'orchard_fruit', 'Apple', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('pear__orchard_fruit', 'orchard_fruit', 'Pear', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('plum__orchard_fruit', 'orchard_fruit', 'Plum', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('apricot__orchard_fruit', 'orchard_fruit', 'Apricot', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('banana__tropical_citrus', 'tropical_citrus', 'Banana', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('pineapple__tropical_citrus', 'tropical_citrus', 'Pineapple', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('mango__tropical_citrus', 'tropical_citrus', 'Mango', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('lemon_zest__tropical_citrus', 'tropical_citrus', 'Lemon Zest', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('heather_honey__floral_honeyed', 'floral_honeyed', 'Heather Honey', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('rose__floral_honeyed', 'floral_honeyed', 'Rose', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('elderflower__floral_honeyed', 'floral_honeyed', 'Elderflower', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('beeswax__floral_honeyed', 'floral_honeyed', 'Beeswax', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('butter__buttery_creamy', 'buttery_creamy', 'Butter', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('cream__buttery_creamy', 'buttery_creamy', 'Cream', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('custard__buttery_creamy', 'buttery_creamy', 'Custard', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('fudge__buttery_creamy', 'buttery_creamy', 'Fudge', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('struck_match__meaty_sulphury', 'meaty_sulphury', 'Struck Match', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('broth__meaty_sulphury', 'meaty_sulphury', 'Broth', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('cooked_meat__meaty_sulphury', 'meaty_sulphury', 'Cooked Meat', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('gunpowder__meaty_sulphury', 'meaty_sulphury', 'Gunpowder', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('vanilla__vanilla_coconut', 'vanilla_coconut', 'Vanilla', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('coconut__vanilla_coconut', 'vanilla_coconut', 'Coconut', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('toasted_oak_sweetness__vanilla_coconut', 'vanilla_coconut', 'Toasted Oak Sweetness', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('cinnamon__baking_spice', 'baking_spice', 'Cinnamon', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('clove__baking_spice', 'baking_spice', 'Clove', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('nutmeg__baking_spice', 'baking_spice', 'Nutmeg', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('ginger__baking_spice', 'baking_spice', 'Ginger', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('black_pepper__pepper_tannin', 'pepper_tannin', 'Black Pepper', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('oak_tannin__pepper_tannin', 'pepper_tannin', 'Oak Tannin', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('black_tea__pepper_tannin', 'pepper_tannin', 'Black Tea', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('rye_pepper__pepper_tannin', 'pepper_tannin', 'Rye Pepper', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('raisin__dried_fruit_walnut', 'dried_fruit_walnut', 'Raisin', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('fig__dried_fruit_walnut', 'dried_fruit_walnut', 'Fig', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('date__dried_fruit_walnut', 'dried_fruit_walnut', 'Date', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('walnut__dried_fruit_walnut', 'dried_fruit_walnut', 'Walnut', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('toffee__treacle_roast', 'treacle_roast', 'Toffee', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('treacle__treacle_roast', 'treacle_roast', 'Treacle', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('coffee__treacle_roast', 'treacle_roast', 'Coffee', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('dark_chocolate__treacle_roast', 'treacle_roast', 'Dark Chocolate', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('char__treacle_roast', 'treacle_roast', 'Char', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('old_leather__leather_polished_oak', 'leather_polished_oak', 'Old Leather', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('tobacco__leather_polished_oak', 'leather_polished_oak', 'Tobacco', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('waxed_wood__leather_polished_oak', 'leather_polished_oak', 'Waxed Wood', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('dried_herbs__leather_polished_oak', 'leather_polished_oak', 'Dried Herbs', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('bonfire__woodsmoke', 'woodsmoke', 'Bonfire', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('ash__woodsmoke', 'woodsmoke', 'Ash', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('smoked_meat__woodsmoke', 'woodsmoke', 'Smoked Meat', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('embers__woodsmoke', 'woodsmoke', 'Embers', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('tar__tar_iodine', 'tar_iodine', 'Tar', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('iodine__tar_iodine', 'tar_iodine', 'Iodine', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('antiseptic__tar_iodine', 'tar_iodine', 'Antiseptic', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('creosote__tar_iodine', 'tar_iodine', 'Creosote', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('kippers__tar_iodine', 'tar_iodine', 'Kippers', 4)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('sea_salt__brine_shoreline', 'brine_shoreline', 'Sea Salt', 0)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('seaweed__brine_shoreline', 'brine_shoreline', 'Seaweed', 1)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('oyster_shell__brine_shoreline', 'brine_shoreline', 'Oyster Shell', 2)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
insert into flavour_descriptors (slug, category_slug, name, sort_order) values ('wet_stone__brine_shoreline', 'brine_shoreline', 'Wet Stone', 3)
  on conflict (slug) do update set category_slug = excluded.category_slug, name = excluded.name, sort_order = excluded.sort_order;
