UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul Cigar Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul Single Cask';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glencadam 13YO Sauternes Cask Finish';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glencadam 15YO The Rather Dignified';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glencadam 15YO Madeira Cask Finish';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glencadam 15YO White Port Cask Finish';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Frank McHardy Bunnahabhain 12YO Single Cask';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bunnahabhain 15YO SG60 2009 Ruby Port Cask #54';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bunnahabhain 2009 Ruby Port Cask #55';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bunnahabhain Feis IIe 2023 Canasta Cask Matured';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bunnahabhain 12YO Cask Strength';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Frank McHardy Aberfeldy 15YO Single Cask';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Volar';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Nostalgia';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Reserve No.6';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Reserve No.7';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Equinox';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Bal Masque';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Dragon Series 2 The Spirit';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Dragon Series 1 The Field';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Liora';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Lochlea Cask Strength Bath 1 2023 Cask Strength Bath 1';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Lochlea Cask Strength Bath 2 2024 Cask Strength Bath 2';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Lochlea Cask Strength Bath 3 2025 Cask Strength Bath 3';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Cu Bocan 15YO';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Currach Atlantic Kombu Pandanus Cask Finsh';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Currach Atlantic Kombu Apple Ice Wine Cask';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Currach Atlantic Kombu Mezcal Cask';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Currach Atlantic Kombu PX Cask';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Currach Atlantic Wakame Sake Cask Finish';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Frank McHardy Teaninich 14YO 14YO Distilled 2009 Bottled 2023';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Frank McHardy Ardmore 11YO 11YO Distilled 2009';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Single Cask Single Cask (Singapore Exclusive)';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Signature Series Signature Series Edition 2 Barrel Bonfire';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Signature Series Signature Series Edition 3 Duero Discovery';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Signature Series Signature Series Edition 1 Remnant Renegade';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul 14YO Cognac Cognac Cask Finsk';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul 14YO 2008 Cask No.1775 Single Cask (Cask No.1775)';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul 14YO White Port Cask Finsih White Port Cask Finish';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul 15YO Tawny Port Finish Tawny Port Cask Finish';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul 15YO Madeira Cask Finish';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Tomintoul 15YO Peaty Tang';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Tipperary Own Barley Friends of Quannich Bar 2022 Single Cask';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Cadenhead Enigma Lowland Single Malt 11YO Enigma Series';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Cadenhead Royal Brackla 13YO Cask Strength';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cadenhead Inchgower 13YO Cask Strength';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Lochlea 6 YO Bottled From 6 Hand-Selected Casks';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Deanston 12YO 2006 Fino Cask Finish Fino Sherry Cask Finish';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Deanston 15YO 2007 Tequila Cask Tequila Cask Finish';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Deanston 15YO Organic Whisky Organic';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Lagg Single Malt Inaugural Release Inaugural Release - Batch 1';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Ledaig Hebridean Moon';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Ledaig Triple Wood';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Tipperary 2017 Home Grown Barley Port Cask Port Cask Finish';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Tipperary 2017 Home Grown Barley Mezcal Cask Mezcal Cask Finish';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Tipperary 2017 Home Grown Barley Sake Cask Sake Cask Finish';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Tipperary 2018 Home Grown Barley Pot Still Rioja Pot Still - Rioja Cask Finish';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Tipperary Home Grown Barley Port Cask SG Port Cask Finish (Friends of Quaich Bar 2023)';
UPDATE public.whiskies SET region = 'Ireland' WHERE name = 'Tipperary Home Grown Barley Rioja & Mezcal Rioja and Mezcal Finish (SG60)';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cadenhead OC4 Inchgower 12YO Bourbon, Sherry & Madeira Hogshead';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cadenhead OC5 Glenlossie-Glenlivet 12YO Bourbon Hogshead';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Cadenhead OC7 Glencadam 10YO Original Collection Standard';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Cadenhead OC8 Tullibardine 12 YO Original Collection Standard';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cadenhead OC9 Glenburgie-Glenlivet 13YO Bourbon & Port Cask';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin 12YO The Italian Collection Amarone Italian Collection - Amarone Cask';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin 12YO The Italian Collection Barolo Italian Collection - Barolo Cask';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin 12YO The Italian Collection Marsala Italian Collection - Marsala Cask';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin Five Virtues Metal Five Virtues Series - Metal';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin 14YO Port Cask Port Cask Finish';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin 12YO 2008 Rivesaltes Cask French Collection - Rivesaltes Cask';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Kairos Kairos Edition';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Edition Resfeber Resfeber Edition';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Reserve No.3';
UPDATE public.whiskies SET region = 'England' WHERE name = 'The Lakes Whiskymaker''s Editions Reserve No.5';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Longrow 100 Proof Batch 1 100 Proof (Batch 1)';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Old Ballantruan 15YO Peated Malt';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Hazelburn Olorosso Cask';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Hazelburn Olorosso Cask';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Hazelburn Olorosso Cask';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin SG 60 Exclusive Cab. Sauv';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin Whisky Journey Exclusive';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin Portuguese Collection Moscatel';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin Decades II Softer Side';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin Sherry Collection Palo Cortado';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin French Collection Sauternes';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Select Casks Quaich Red Wine';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch 2023 Release Olorosso 14';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Iteration IV the Ageing Dragon Series';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Select Casks Quaich Olorosso';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Iteration V The Decision Dragon Series';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Bladnoch Iteration III The Casks Dragon Series';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Octave Holyrood 2021 3yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Craigellachie 2011 13yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Glenrothes 2013 10yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Octave Brackla 2011 12yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Miltonduff 2011 12yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Octave Tullibardine 2013 11yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Glentauchers 2008 15yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Octave Bunnahabhain Peated 2014 9yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Octave Ben Nevis 2012 12yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Glentauchers 2011 13yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Octave Royal Brackla 2014 10yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Octave Caol Ila 2008 16yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Iconic Speyside 2011 13yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor DTSC Brackla 2011 12yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor DTSC Ben Nevis 2012 11yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor DTSC Glenallachie 2008 14yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor RAG North British 1991 32yo Single Grain';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull Kyloe Blended Scotch — Sample';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull 14yo Peated Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull 14yo Peated Blended Scotch';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Arran 25yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Glenfiddich Glenfiddich Mr Porter Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Aberlour Aberlour Cask Annamh V1 Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Arran 24yo TWS Single Cask Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cragganmore Cragganmore Distillers Edition 2017 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Berry Bros & Rudd BBR Teaninich 33yo 1983 Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Arran Harmony Ed.4 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Fettercairn Fettercairn Glenkeir Festival Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Grant''s Grant''s Triple Wood Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glen Garioch Glen Garioch 12yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Spearhead Spearhead Single Grain Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Chivas Regal Chivas Regal Extra Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Aberfeldy Aberfeldy 12yo Single Malt';
UPDATE public.whiskies SET region = 'Japan' WHERE name = 'Nikka Nikka Pure Malt Whisky Set';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Springbank Springbank 10yo Cage Bottling Single Malt';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Kilkerran Kilkerran Handfill 2021 Single Malt';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Glen Scotia Glen Scotia 12yo Seasonal Edition Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bruichladdich Port Charlotte Distillery Valinch RDC Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bunnahabhain Bunnahabhain Feis 2020 Amontillado Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glengoyne Glengoyne Distillery Edition Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Woven Whisky Woven Exp.2 Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Woven Whisky Woven Exp.3 Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Woven Whisky Woven Exp.4 Blended Scotch';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Springbank Springbank Machrihanish Edition Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Glenfiddich Glenfiddich Festival Experiment Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Glenfiddich Glenfiddich Winter Storm Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Macallan Macallan Harmony Rich Cacao Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bruichladdich Bruichladdich Feis 2021 Origins Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bruichladdich Bruichladdich Feis Rockindaal 01 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bruichladdich Bruichladdich Feis Rockindaal 2 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'AnCnoc AnCnoc 12yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Craigellachie Craigellachie 13yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Glenfiddich Glenfiddich Orchard Experiment Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Woven Whisky Woven Edition 6 Spirited Blended Scotch';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'GlenAllachie GlenAllachie 15yo Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Jura Jura 12yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Woven Whisky Woven Experience No.5 Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Speyburn Speyburn 15yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Asian Golf Scotland Bunnahabhain 10yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Asian Golf Scotland Tullibardine 11yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Asian Golf Scotland Glenallachie 13yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Ben Nevis Ben Nevis MacDonalds Traditional Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'GlenDronach GlenDronach Ode to Embers Peated Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'GlenDronach GlenDronach Ode to Dark Single Malt';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Kilkerran Kilkerran 8yo Cask Strength Single Malt';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Springbank Springbank 15yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Octave Campbeltown 2014 11yo Blended Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Dalmunach 2016 8yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Teaninich 2015 10yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Mannochmore 2015 10yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Iconic Speyside 2011 14yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor DTSC Glen Moray 2007 15yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor DTSC Auchindoun 2008 16yo Blended Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull Kyloe Sherry Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull Kyloe Rum Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull 10yo Rum Finish Blended Scotch';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Battlehill Teaninich 9yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Battlehill Ben Nevis 12yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Battlehill Miltonduff 12yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Battlehill Royal Brackla 10yo Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor Battlehill Auchentoshan 12yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Battlehill An Islay 15yo Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor Octave Invergordon 2011 13yo Single Grain';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Lonach Highland Games 2024 Tullibardine 11yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor DTSC Glen Moray 2007 16yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor DTSC Holyrood 2021 3yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor DTSC Bunnahabhain 2008 14yo Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor RAG Invergordon 2009 15yo Single Grain';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor DTSC An Islay 2007 16yo Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor RAG Caledonian 1987 34yo Single Grain';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Big Smoke 50 Blended Malt Scotch';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Ardbeg Ardbeg Corryvrechan Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'AnCnoc AnCnoc 12yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Ardnahoe Ardnahoe Bholsa Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Ardnamurchan Ardnamurchan Cask Strength Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bunnahabhain Bunnahabhain Toiteach A Dha Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Cardhu Cardhu 14yo Special Release 2021 Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Arran Arran Rare Batch 15yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Benromach Benromach Contracts Peat Smoke 2014 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomatin Tomatin TSE Exclusive 2009 15yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'GlenAllachie GlenAllachie 9yo Oloroso Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'GlenAllachie GlenAllachie 10yo Cask Strength Batch 12 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'GlenAllachie GlenAllachie 15yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'GlenAllachie GlenAllachie Single Cask 2012 12yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'BenRiach BenRiach Smoky 12yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glencadam Glencadam Reserva De Porto Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glenmorangie Glenmorangie Quinta Ruban 14yo Single Malt';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Glen Scotia Glen Scotia Rubia Del Duero 9yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glenglassaugh Glenglassaugh Rare Cask 10yo UK Exclusive Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Highland Park Highland Park 15yo Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Highland Park Highland Park Cask Strength Batch 3 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Mortlach Mortlach The Wee Witchie 12yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Kilchoman Kilchoman Fino Sherry Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cragganmore Cragganmore Distillers Edition Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Ledaig Ledaig Hebridean Moon Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Roseisle Roseisle 12yo Special Release 24 Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Talisker Talisker Distillers Edition Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomintoul Tomintoul Cigar Malt Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Tomintoul Tomintoul Tawny Port Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Clynelish Clynelish 14yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Glengoyne Glengoyne Cask Strength Batch 10 Single Malt';
UPDATE public.whiskies SET region = 'Islands' WHERE name = 'Tobermory Tobermory 12yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Singleton Singleton 15yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Mortlach Mortlach Natural Cask Single Malt';
UPDATE public.whiskies SET region = 'Japan' WHERE name = 'Naahama Single Malt Naahama Japanese Whisky 2019';
UPDATE public.whiskies SET region = 'Poland' WHERE name = 'ROK ROK 1782 Zak J.A. Baczewski';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Edradour Edradour Vintage 1999 Cask No.3021';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bowmore Bowmore 16yo Ruby Post Cask Finish Single Malt';
UPDATE public.whiskies SET region = 'New Zealand' WHERE name = 'The Cardrona The Cardrona Single Malt The Falcon';
UPDATE public.whiskies SET region = 'Japan' WHERE name = 'The Chuan The Chuan Pure Malt Whisky Emeishan';
UPDATE public.whiskies SET region = 'Australia' WHERE name = 'Starward Starward Small Batch 171113-WH';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Springbank Springbank Cask Strength 12yo Campbeltown';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Lagavulin Lagavulin Islay Single Malt Double Matured 2002';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Octave Dalmore 2006 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor DFW 34yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor DTSC Bunnahabhain 19yo Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor WS Strathclyde 1990 Single Grain';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Octave Dalmunach 2015 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Mortlach Mortlach Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'The Wealth Spirit The Wealth Spirit 28yo Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Auchentoshan Auchentoshan Single Malt';
UPDATE public.whiskies SET region = 'Vietnam' WHERE name = 'Hoiana Hoiana 18yo';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Gordon & MacPhail Gordon & MacPhail 1981 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Gordon & MacPhail Gordon & MacPhail 1994 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Laphroaig Royal AE Laphroaig 2005 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Laphroaig Royal AE Laphroaig 2005 Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor DTSC Caledonian 34yo Single Grain';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor DPS Auchentoshan 2011 14yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Bruichladdich Bruichladdich Islay Barley 2011 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull Faldo 30yo Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Battlehill The Huntly 24yo Blended Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Duncan Taylor Aultmore 2008 13yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Duncan Taylor Aultmore 2008 13yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Duncan Taylor Laphroaig 2005 16yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Duncan Taylor Glen Moray 14yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Duncan Taylor Tormore 2010 11yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Duncan Taylor Tormore 2010 11yo Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Duncan Taylor Braeval 2000 22yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull 21yo Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Black Bull Kyloe Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Whiskies of Scotland Blair Athol 1989 Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Whiskies of Scotland Blair Athol 1989 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bowmore 1998 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bowmore 1998 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bruichladdich 1992 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bruichladdich 1992 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bunnahabhain 1989 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bunnahabhain 1989 Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bunnahabhain 1991 46.9% Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bunnahabhain 1991 46.9% Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bunnahabhain 1991 46% Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Duncan Taylor Whiskies of Scotland Bunnahabhain 1991 46% Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Grant 1995 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Grant 1995 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Moray 1989 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Moray 1989 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Moray 1991 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Moray 1991 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Moray 1994 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glen Moray 1994 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glenlossie 1992 49.6% Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glenlossie 1992 49.6% Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glenlossie 1992 50.7% Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glenlossie 1992 50.7% Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glenlossie 1998 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Glenlossie 1998 Single Malt';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor Whiskies of Scotland Strathclyde 1990 Single Grain';
UPDATE public.whiskies SET region = 'Lowland' WHERE name = 'Duncan Taylor Whiskies of Scotland Strathclyde 1990 Single Grain';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Strathmill 1990 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Duncan Taylor Whiskies of Scotland Strathmill 1990 Single Malt';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Imperious Imperious Miltonduff 1990 30yo Single Malt';
UPDATE public.whiskies SET region = 'Islay' WHERE name = 'Imperious Imperious Bunnahabhain 1991 30yo Single Malt';
UPDATE public.whiskies SET region = 'USA' WHERE name = 'Imperious Imperious Glenrothes Bourbon 40yo Single Malt';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Duncan Taylor 12yo Special Edition Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Duncan Taylor 12yo Special Edition Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Duncan Taylor 5 Star Special Edition Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Duncan Taylor Duncan Taylor 18yo Special Edition Blended Scotch';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Cadenhead OC10 Knockdhu 10YO Original Collection (Bourbon/Oloroso Sherry)';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Cadenhead OC13 Kilkerran 13YO 50% Bourbon / 50% Ruby Port';
UPDATE public.whiskies SET region = 'Highland' WHERE name = 'Cadenhead OC13 Macduff 13YO 13YO Bourbon';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cadenhead OC4 Auchroisk 14YO 14YO Auchroisk';
UPDATE public.whiskies SET region = 'Speyside' WHERE name = 'Cadenhead OC2 Tomintoul Glenlivet 14YO Refill Sherry Butts';
UPDATE public.whiskies SET region = 'Campbeltown' WHERE name = 'Cadenhead OC3 The English Distillery 12YO 12YO Bourbon The English Distillery Company';
